services:
  - type: web
    name: whatshap-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    staticPublishPath: ./images
    routes:
      - type: rewrite
        source: /*
        destination: /index.html