services:
  - type: web
    name: whatshap-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5001
    staticPublishPath: ./images